name: Order Microservice CI
on:
  push:
    branches:
      - "main"
    paths:
      - "order-microservice/**"
  pull_request:
    branches:
      - "main"

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        uses: npm ci
        working-directory: "./order-microservice"

      - name: Run Tests
        uses: npm test
        working-directory: "./order-microservice"