name: User Microservice CI
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "user-microservice/**"
  pull_request:
    branches:
      - "main"

jobs:
  
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: "./user-microservice/package-lock.json"

      - name: Install Dependencies
        run: npm ci
        working-directory: "./user-microservice"
        
      - name: Run Tests
        run: npm test
        working-directory: "./user-microservice"
