name: User Microservice CI
on:
  push:
    branches:
      - "main"
    paths:
      - "user-microservice/**"
  pull_request:
    branches:
      - "main"

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm ci
        working-directory: "./user-microservice"
        
      - name: Run Tests
        run: npm test
        working-directory: "./user-microservice"
